/** 提供 Agent 统计纯展示测试使用的完整 read model。 */

import type { AgentStatistics } from "../../statistics/domain/types";

export const agentStatisticsFixture: AgentStatistics = {
  generated_at: "2026-08-03T12:00:00Z",
  window_start: "2026-08-03T00:00:00+08:00",
  window_end: "2026-08-04T00:00:00+08:00",
  timezone: "Asia/Shanghai",
  sample_size: 2,
  quality: "partial",
  freshness: {
    agent_sessions: { updated_at: "2026-08-03T11:30:00Z", status: "fresh" },
  },
  statuses: {
    completed: 1,
    running: 0,
    interrupted: 1,
    failed: 0,
    unknown: 0,
  },
  tokens: {
    input: 300_000,
    output: 12_000,
    cache_read: 270_000,
    cache_creation: null,
    reasoning: null,
    unknown: null,
    total: 312_000,
    total_includes_cache_input: true,
    known_session_count: 2,
    session_count: 2,
    quality: "partial",
  },
  first_visible_response: {
    sample_size: 24,
    p50_ms: 14_700,
    p95_ms: 81_800,
    p99_ms: null,
    quality: "reliable",
  },
  activity: {
    session_sum_ms: 7_200_000,
    concurrent_union_ms: 5_400_000,
    quality: "reliable",
  },
  cache_input_ratio: 270_000 / (220_000 + 80_000 + 60_000 + 8_000),
  model_summaries: [
    {
      runtime: "codex",
      model: "gpt-5.6-sol",
      session_count: 1,
      statuses: {
        completed: 1,
        running: 0,
        interrupted: 0,
        failed: 0,
        unknown: 0,
      },
      tokens: {
        input: 220_000,
        output: 10_000,
        cache_read: 210_000,
        cache_creation: null,
        reasoning: 4_000,
        unknown: null,
        total: 230_000,
        total_includes_cache_input: true,
        known_session_count: 1,
        session_count: 1,
        quality: "reliable",
      },
      first_visible_response: {
        sample_size: 20,
        p50_ms: 12_000,
        p95_ms: 80_000,
        p99_ms: null,
        quality: "reliable",
      },
      cache_input_ratio: 0.9545,
      activity_ms: 3_600_000,
      quality: "reliable",
    },
    {
      runtime: "claude_code",
      model: "glm-5.2",
      session_count: 1,
      statuses: {
        completed: 0,
        running: 0,
        interrupted: 1,
        failed: 0,
        unknown: 0,
      },
      tokens: {
        input: 80_000,
        output: 2_000,
        cache_read: 60_000,
        cache_creation: 8_000,
        reasoning: null,
        unknown: null,
        total: 82_000,
        total_includes_cache_input: true,
        known_session_count: 1,
        session_count: 1,
        quality: "partial",
      },
      first_visible_response: {
        sample_size: 4,
        p50_ms: null,
        p95_ms: null,
        p99_ms: null,
        quality: "unavailable",
      },
      cache_input_ratio: 60_000 / (80_000 + 60_000 + 8_000),
      activity_ms: 3_600_000,
      quality: "partial",
    },
  ],
  sessions: [
    {
      session_id: "trowel-session-codex",
      runtime: "codex",
      models: ["gpt-5.6-sol"],
      started_at: "2026-08-03T10:00:00Z",
      activity_ms: 3_600_000,
      first_visible_response: {
        sample_size: 20,
        p50_ms: 12_000,
        p95_ms: 80_000,
        p99_ms: null,
        quality: "reliable",
      },
      tokens: {
        input: 220_000,
        output: 10_000,
        cache_read: 210_000,
        cache_creation: null,
        reasoning: 4_000,
        unknown: null,
        total: 230_000,
        total_includes_cache_input: true,
        known_session_count: 1,
        session_count: 1,
        quality: "reliable",
      },
      status: "completed",
      quality: "reliable",
    },
    {
      session_id: "trowel-session-claude",
      runtime: "claude_code",
      models: ["glm-5.2"],
      started_at: "2026-08-03T09:00:00Z",
      activity_ms: 3_600_000,
      first_visible_response: {
        sample_size: 4,
        p50_ms: null,
        p95_ms: null,
        p99_ms: null,
        quality: "unavailable",
      },
      tokens: {
        input: 80_000,
        output: 2_000,
        cache_read: 60_000,
        cache_creation: 8_000,
        reasoning: null,
        unknown: null,
        total: 82_000,
        total_includes_cache_input: true,
        known_session_count: 1,
        session_count: 1,
        quality: "partial",
      },
      status: "interrupted",
      quality: "partial",
    },
  ],
};
