"""file-backed memory store (slice-038).

Reads/writes the dual-track markdown tree under ``root``:

    root/
      core.md            layer one (always-injected imperatives)
      notes/*.md         knowledge track (layer-two notes)
      dictionary-L0.md   root index (regenerated by slice-041)
      dictionary-L1/     per-domain indexes
      diary/{daily,weekly,monthly}/   experience track

Layer one has NO general write API here (C-5) — only ``seeds.bootstrap_core``
performs the one-time, idempotent seed write. The write loop (040) writes
notes/diary; the read loop (039) reads everything; the tidy loop (041)
rewrites/retires. This module is the shared substrate.
"""
from __future__ import annotations

import datetime
import hashlib
import logging
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml

from trowel_py.memory.draft import DraftDiary
from trowel_py.memory.profile import (
    body_to_profile,
    empty_profile,
    profile_to_body,
    validate_profile,
)
from trowel_py.memory.schema import validate_entry
from trowel_py.memory.types import CoreItem, Diary, Note, NoteId, PersistContext, Profile

logger = logging.getLogger(__name__)

_NOTES_DIR = "notes"
_DIARY_DIR = "diary"
_EPISODES_DIR = "episodes"
_CORE_FILE = "core.md"
_PROFILE_FILE = "profile.md"
_DICT_L0 = "dictionary-L0.md"

# schema layer value (day|week|month) → 038 storage-layout directory name.
# load_diary reads by frontmatter ``layer`` (not dir name), so the two stay
# decoupled; this map keeps write_diary consistent with the 038 convention.
_LAYER_DIR = {"day": "daily", "week": "weekly", "month": "monthly"}

# Stable, readable key order for serialized note frontmatter.
# slice-041: confidence + retired removed (C-9); memory_id/status/supersedes/
# helpful_refs/harmful_refs/trigger/sources added (correction + lifecycle).
_NOTE_KEY_ORDER = (
    "type", "title", "kind", "tags", "summary",
    "created", "updated",
    "verification", "verification_reason",
    "pain", "pain_reason", "conflicts_with",
    "memory_id", "status",
    "supersedes", "superseded_by",
    "valid_from", "last_verified_at",
    "refs", "helpful_refs", "harmful_refs", "last_ref",
    "trigger", "do_not_use_when",
    "sources", "source_sessions", "content_hash",
)


class MemoryStore:
    """Read/write the memory tree rooted at ``root``.

    Args:
        root: the memory root directory (e.g. ``~/.trowel/memory``).
    """

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root)

    # ---- layer one (core) ----
    def load_core(self) -> str:
        """Return core.md full text (empty string if absent). For 039 injection.

        The file carries the imperatives twice: structured in the frontmatter
        ``items`` (the authoritative source 039 should parse) and mirrored in a
        readable numbered body (for humans). If a human edits only the body,
        the two can drift — 039 should treat the frontmatter ``items`` as
        authoritative.
        """
        path = self.root / _CORE_FILE
        return path.read_text(encoding="utf-8") if path.exists() else ""

    # ---- knowledge track (notes) ----
    def load_notes(self, filter: dict[str, Any] | None = None) -> list[Note]:
        """Return all notes (including retired — C-4 retirement ≠ deletion).

        Args:
            filter: optional ``{"status": str}`` (slice-041 lifecycle) and/or
                ``{"tag": str}`` to narrow the set. ``{"retired": bool}`` is
                kept as a legacy alias (retired=True → status=="retired").

        Note:
            Files with no/invalid frontmatter, or whose type is not ``note``,
            are skipped with a warning (W4) — a hand-corrupted note should not
            silently vanish from injection.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return []
        notes: list[Note] = []
        for p in sorted(notes_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if fm is None:
                logger.warning("note %s has no/invalid frontmatter, skipped", p.name)
                continue
            note = _note_from_fm(fm, body)
            if note is None:
                logger.warning("note %s frontmatter type is not 'note', skipped", p.name)
                continue
            notes.append(note)
        if filter:
            notes = [n for n in notes if _matches(n, filter)]
        return notes

    def load_note(self, note_id: NoteId) -> Note | None:
        """Return one note by filename-stem id, or None if absent/invalid.

        slice-040-c: the read tool opens a note by id; this loads one file
        instead of scanning the whole corpus.
        """
        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            return None
        fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if fm is None:
            return None
        return _note_from_fm(fm, body)

    def load_notes_with_id(
        self, filter: dict[str, Any] | None = None
    ) -> list[tuple[NoteId, Note]]:
        """Return ``(note_id, Note)`` pairs (id = filename stem).

        slice-040-c: dictionary clustering needs the stem alongside the note.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return []
        out: list[tuple[NoteId, Note]] = []
        for p in sorted(notes_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if fm is None:
                continue
            note = _note_from_fm(fm, body)
            if note is None:
                continue
            out.append((p.stem, note))
        if filter:
            out = [(i, n) for i, n in out if _matches(n, filter)]
        return out

    def write_note(self, entry: dict[str, Any]) -> NoteId:
        """Validate (C-2/C-3) and persist a note. Returns its filename-stem id.

        Wiki-compatible fields beyond the known set (e.g. ``sources``/``related``)
        are preserved (W3): the known keys are emitted in a stable readable
        order, any unknown keys follow. This keeps write_note symmetric with
        ``record_ref`` (which already preserves unknown keys) and honors the
        "reuse the wiki-compatible subset" intent when migrating wiki notes.

        Raises:
            ValueError: the entry fails schema validation.
        """
        result = validate_entry("note", entry)
        if not result.ok:
            raise ValueError(f"invalid note: {result.errors}")
        slug = self._unique_slug(str(entry.get("title", "")).strip())
        fm = _ordered_note_frontmatter(entry)
        path = self.root / _NOTES_DIR / f"{slug}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_dump_frontmatter(fm, entry.get("__body", "")), encoding="utf-8")
        return slug

    def write_diary(self, entry: dict[str, Any]) -> str:
        """Validate (C-2) and persist a diary entry. Returns its date stem.

        The file lands under ``diary/{daily|weekly|monthly}/{date}.md`` — the
        directory name follows the 038 storage-layout convention, while the
        frontmatter ``layer`` value stays the schema value (``day|week|month``).
        ``write_diary`` maps layer→dir so callers always pass the schema layer.

        The event-stream body is passed via the ``__body`` internal channel
        (same convention as ``write_note``); it lands in the file body, not in
        frontmatter. Same-date writes overwrite (a diary day is one file).

        Raises:
            ValueError: the entry fails schema validation (e.g. missing date,
                illegal layer).
        """
        fm = {k: v for k, v in entry.items() if not k.startswith("__")}
        fm["type"] = "diary"
        result = validate_entry("diary", fm)
        if not result.ok:
            raise ValueError(f"invalid diary: {result.errors}")
        layer = str(fm.get("layer", "day"))
        date = str(fm.get("date", ""))
        dir_name = _LAYER_DIR.get(layer, "daily")
        path = self.root / _DIARY_DIR / dir_name / f"{date}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_dump_frontmatter(fm, entry.get("__body", "")), encoding="utf-8")
        return date

    def record_ref(self, note_id: NoteId, date: str) -> None:
        """Increment refs and stamp last_ref on an existing note (retirement input).

        slice-040-c: per-note ``fcntl.flock`` so concurrent MCP servers don't
        lose refs increments (read-modify-write race — access-log append is
        atomic via O_APPEND, but the refs rewrite is not).

        Raises:
            FileNotFoundError: no note with that id.
        """
        import fcntl

        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            raise FileNotFoundError(note_id)
        with path.open("r+", encoding="utf-8") as f:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
            try:
                fm, body = _split_frontmatter(f.read())
                if fm is None:
                    raise ValueError(f"note {note_id!r} has no frontmatter")
                fm["refs"] = int(fm.get("refs") or 0) + 1
                fm["last_ref"] = date
                f.seek(0)
                f.truncate()
                f.write(_dump_frontmatter(fm, body))
            finally:
                fcntl.flock(f.fileno(), fcntl.LOCK_UN)

    def find_note_by_source(self, cc_session_id: str, content_hash: str) -> NoteId | None:
        """Return the id of the note from ``cc_session_id`` with this content_hash.

        slice-040-a idempotence key (D4): ``(cc_session_id, content_hash)``. A
        re-run with the same source+content finds the existing note so persist
        updates mutable fields instead of duplicating. Returns ``None`` when no
        note carries that source session + hash (existing 45 notes predate this
        field and are skipped — they simply become new writes once).

        TODO(041): this is O(n) per call — ``persist_draft`` calls it once per
        draft note, so the whole landing is O(notes × existing_notes). Fine at
        the current corpus size (tens); build an in-memory
        ``(cc_session_id, content_hash) → id`` index when notes reach hundreds.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return None
        for p in sorted(notes_dir.glob("*.md")):
            fm, _body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if not fm:
                continue
            sources = fm.get("source_sessions") or []
            if cc_session_id in sources and fm.get("content_hash") == content_hash:
                return p.stem
        return None

    def update_note_fields(self, note_id: NoteId, fields: dict[str, Any]) -> None:
        """Read-modify-write a note's frontmatter fields (idempotent re-judge path).

        Only the mutable judgment fields are ever updated this way
        (verification / pain / *_reason / conflicts_with / updated / refs …);
        the title/summary/body/kind identity is stable (their hash is the key).
        Preserves unknown wiki fields and the body (W3 symmetry with record_ref).

        Raises:
            FileNotFoundError: no note with that id.
        """
        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            raise FileNotFoundError(note_id)
        # W5 (auto-cr): flock the read-modify-write — record_ref already locks,
        # so an unlocked update_note_fields (tidy apply / recompute / persist
        # re-judge) racing it could overwrite a fresh refs increment.
        import fcntl

        with path.open("r+", encoding="utf-8") as f:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
            try:
                fm, body = _split_frontmatter(f.read())
                if fm is None:
                    raise ValueError(f"note {note_id!r} has no frontmatter")
                fm.update(fields)
                f.seek(0)
                f.truncate()
                f.write(_dump_frontmatter(fm, body))
            finally:
                fcntl.flock(f.fileno(), fcntl.LOCK_UN)

    # ---- experience track (diary) ----
    def load_diary(self, since: str | None = None,
                   layer: str | None = None) -> list[Diary]:
        """Return diary entries, optionally filtered by date floor and layer.

        ``since`` is a lexicographic floor on the ``date`` string (inclusive);
        callers should use ISO ``YYYY-MM-DD`` dates so the ordering is correct
        (W2 — the schema does not yet enforce ISO format).
        """
        diary_root = self.root / _DIARY_DIR
        if not diary_root.exists():
            return []
        out: list[Diary] = []
        for p in sorted(diary_root.rglob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            d = _diary_from_fm(fm, body)
            if d is None:
                continue
            if layer and d.layer != layer:
                continue
            if since and d.date < since:
                continue
            out.append(d)
        return out

    # ---- experience track (episodes) — slice-040-a ----
    def write_episode(
        self, context: PersistContext, diary_entries: tuple[DraftDiary, ...]
    ) -> str:
        """Upsert one segment into ``episodes/<cc_session_id>.md`` (C-1).

        One source session maps to exactly one episode file; the file may hold
        multiple segments (040-b incremental re-runs). This call upserts the
        ``context.segment_id`` segment: a same-id segment replaces only its own
        body, a new-id segment is appended — an existing sibling segment is
        never clobbered, so the original experience is never lost.

        ``diary_entries`` come straight from the distilled DraftDiary tuple; a
        session whose agent returned zero events still gets a skeletal segment
        flagged ``empty_reason`` (no silent skip → no lost provenance).

        Returns:
            the ``cc_session_id`` (the episode filename stem).
        """
        path = self.root / _EPISODES_DIR / f"{context.cc_session_id}.md"
        path.parent.mkdir(parents=True, exist_ok=True)

        if path.exists():
            fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
            fm = fm or {}
            blocks = _parse_segment_blocks(body)
            segs = list(fm.get("segments") or [])
            prior_dates = set(fm.get("activity_dates") or [])
        else:
            fm, body = {}, ""
            blocks = _parse_segment_blocks(body)
            segs = []
            prior_dates = set()

        block_text, content_hash, dates, empty_reason = _render_segment(
            context.segment_id, diary_entries
        )
        # upsert block (preserve insertion order; replace in place if exists)
        blocks[context.segment_id] = block_text
        # upsert segment metadata (replace in place, else append)
        seg_meta: dict[str, Any] = {
            "segment_id": context.segment_id,
            "start_offset": context.source_start_offset,
            "end_offset": context.source_end_offset,
            "review_date": context.review_date,
            "content_hash": content_hash,
            # slice-061: per-segment activity dates + basis drive the daily
            # projection (block-4). review_date is kept for back-compat reads
            # but no longer routes daily.
            "activity_dates": list(context.activity_dates),
            "date_basis": context.date_basis,
            "processed_date": context.processed_date,
        }
        if empty_reason:
            seg_meta["empty_reason"] = empty_reason
        new_segs: list[dict[str, Any]] = []
        replaced = False
        for s in segs:
            if s.get("segment_id") == context.segment_id:
                new_segs.append(seg_meta)
                replaced = True
            else:
                new_segs.append(s)
        if not replaced:
            new_segs.append(seg_meta)

        fm_out: dict[str, Any] = {
            "type": "episode",
            "cc_session_id": context.cc_session_id,
            "workdir": context.workdir,
            "registered_at": context.registered_at,
            "review_date": context.review_date,
            "activity_dates": sorted(prior_dates | set(dates)),
            "source_jsonl": context.source_jsonl,
            "segments": new_segs,
        }
        body_out = "".join(blocks.values())
        path.write_text(_dump_frontmatter(fm_out, body_out), encoding="utf-8")
        return context.cc_session_id

    def derive_daily_from_episodes(self, date: str) -> str:
        """Rebuild ``diary/daily/<date>.md`` as the aggregate of that day's episodes.

        slice-061 block-4: the daily is a precise projection — only the
        ``## <date>`` blocks of segments whose ``activity_dates`` include
        ``date`` (C-2 — a resumed/补跑 segment never re-files its content under
        the run day). Delegates to ``project_daily_entries`` (which recovers
        dates from headings for legacy episodes).

        Returns:
            the date stem, or ``""`` when no episode matches (no fabricated
            empty daily — preserves 039's "empty = nothing happened" contract).
        """
        items = self.project_daily_entries(date)
        if not items:
            return ""
        daily_body = "\n\n".join(body for _ts, body in items)
        self.write_diary(
            {
                "type": "diary",
                "date": date,
                "layer": "day",
                "period": date,
                "promoted_knowledge": [],
                "__body": daily_body,
            }
        )
        return date

    def project_daily_entries(self, date: str) -> list[tuple[str, str]]:
        """Project one date's diary entries across all episodes (slice-061 block-4).

        Walk each episode's segments and take ONLY the ``## <date>`` block of
        segments whose ``activity_dates`` include ``date``. A resumed/补跑
        segment whose real activity is another day contributes nothing here
        (C-2). Legacy episodes without ``activity_dates`` meta recover the
        segment's dates from its ``##`` headings.

        Returns:
            ``[(registered_at, entry_body)]`` ordered by registered_at (time).
        """
        eps_dir = self.root / _EPISODES_DIR
        if not eps_dir.exists():
            return []
        items: list[tuple[str, str]] = []
        for p in sorted(eps_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if not fm:
                continue
            registered_at = _coerce_meta_str(fm.get("registered_at"))
            seg_metas = {
                s.get("segment_id"): s
                for s in (fm.get("segments") or [])
                if isinstance(s, dict)
            }
            blocks = _parse_segment_blocks(body)
            if blocks:
                for seg_id, block in blocks.items():
                    entry = _segment_entry_for_date(
                        block, date, seg_metas.get(seg_id, {})
                    )
                    if entry:
                        items.append((registered_at, entry))
            elif _h2_headings(body):
                # bare legacy body that still carries ## <date> headings: slice
                # the matching day (C-2 — never dump a whole multi-day body).
                entry = _extract_h2_block(body, date)
                if entry:
                    items.append((registered_at, entry))
            elif _episode_covers_date(fm, date):
                # bare body with NO date headings at all: attribute the whole
                # body by the top-level activity_dates (review_date is a last
                # resort for the oldest episodes that predate both).
                stripped = body.strip()
                if stripped:
                    items.append((registered_at, stripped))
        items.sort(key=lambda x: x[0])
        return items

    def audit_episode_attribution(self) -> dict[str, Any]:
        """Attribution health across episodes (slice-061 block-5, read-only).

        Counts how many episodes carry per-segment ``activity_dates`` (the
        block-4 precise path) vs legacy ones that rely on heading / top-level
        fallback. Never writes — the read path already tolerates both (block-4
        recovers dates from headings or the top-level field); this is an
        operator-facing health report so the legacy tail is visible.
        """
        eps_dir = self.root / _EPISODES_DIR
        report: dict[str, Any] = {
            "episodes": 0, "with_segment_dates": 0, "legacy": 0,
        }
        if not eps_dir.exists():
            return report
        for p in sorted(eps_dir.glob("*.md")):
            fm, _body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if not fm:
                continue
            report["episodes"] += 1
            segs = [s for s in (fm.get("segments") or []) if isinstance(s, dict)]
            if any(s.get("activity_dates") for s in segs):
                report["with_segment_dates"] += 1
            else:
                report["legacy"] += 1
        return report

    # ---- dictionary ----
    def load_dictionary_L0(self) -> str:
        """Return the L0 root index text (empty string if skeleton absent)."""
        path = self.root / _DICT_L0
        return path.read_text(encoding="utf-8") if path.exists() else ""

    # ---- layer-one items (structured, for slice-039 injection) ----
    def load_core_items(self) -> tuple[CoreItem, ...]:
        """Parse core.md frontmatter items into CoreItem (all, including retired).

        The store stays neutral — retirement filtering is the injection layer's
        job (slice-039 C-1/C-2). Returns () when core.md is absent, has no
        frontmatter, or carries no ``items`` list.
        """
        path = self.root / _CORE_FILE
        if not path.exists():
            return ()
        fm, _body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            return ()
        items = fm.get("items")
        if not isinstance(items, list):
            return ()
        return tuple(
            core_item
            for it in items
            if (core_item := _core_item_from_dict(it)) is not None
        )

    # ---- profile (slice-047) ----
    def load_profile(self) -> Profile:
        """Return the user self-description profile, or an empty Profile if absent.

        C-6: a missing or empty profile.md (or one with no frontmatter) yields
        ``empty_profile()`` — cold-start seeding is 050's job, not the store's.
        Parse is lenient (see ``body_to_profile``): missing/reordered ``##``
        sections degrade to empty strings, never raise.
        """
        path = self.root / _PROFILE_FILE
        if not path.exists():
            return empty_profile()
        fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            return empty_profile()
        return body_to_profile(
            body,
            updated=_coerce_meta_str(fm.get("updated")),
            source=_coerce_meta_str(fm.get("source")) or "user-edit",
        )

    def write_profile(self, p: Profile, *, source: str) -> None:
        """Validate, snapshot the prior version, then overwrite profile.md.

        C-3: every write stamps ``updated`` (from ``p``) and ``source`` (the arg —
        authoritative caller intent for immutability routing; it overrules
        ``p.source``). C-4: an existing file is snapshotted to
        ``meta/profile-history/`` BEFORE the overwrite (insurance, not a
        user-facing rollback feature). Uses bare ``write_text`` like the rest of
        the store — the C-5 "atomic write + flock" invariant was a false premise
        (the store never had it); the snapshot is the real safety net.

        Raises:
            ValueError: the profile or source tag fails validation.
        """
        validate_profile(p, source)
        path = self.root / _PROFILE_FILE
        if path.exists():
            self._snapshot_profile(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        fm = {"updated": p.updated, "source": source}
        path.write_text(_dump_frontmatter(fm, profile_to_body(p)), encoding="utf-8")

    def _snapshot_profile(self, path: Path) -> None:
        """Copy the current profile.md into meta/profile-history/ (C-4 insurance).

        Named after the OLD file's ``(updated, source)`` so a snapshot records
        which version it captured. A same-key collision (e.g. two same-day
        same-source writes) disambiguates with a ``-2``/``-3`` suffix so an
        intermediate version is never silently lost. A missing/unparseable
        frontmatter falls back to ``unknown`` placeholders — the raw bytes are
        still snapshotted (insurance should never fail on a parse error).
        """
        text = path.read_text(encoding="utf-8")
        fm, _body = _split_frontmatter(text)
        updated = _safe_snapshot_name((fm or {}).get("updated"))
        source = _safe_snapshot_name((fm or {}).get("source"))
        hist_dir = self.root / "meta" / "profile-history"
        hist_dir.mkdir(parents=True, exist_ok=True)
        target = hist_dir / f"{updated}-{source}.md"
        n = 2
        while target.exists():
            target = hist_dir / f"{updated}-{source}-{n}.md"
            n += 1
        target.write_text(text, encoding="utf-8")

    # ---- internals ----
    def _unique_slug(self, title: str) -> str:
        base = _slugify(title)
        slug, i = base, 2
        while (self.root / _NOTES_DIR / f"{slug}.md").exists():
            slug, i = f"{base}-{i}", i + 1
        return slug


# ---------------------------------------------------------------- frontmatter IO


def _split_frontmatter(text: str) -> tuple[dict[str, Any] | None, str]:
    """Split a ``---``-delimited YAML frontmatter block from the body.

    Returns:
        (frontmatter dict or None, body text). None frontmatter when the file
        has no well-formed leading block.
    """
    if not text.startswith("---"):
        return None, text
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return None, text
    fm_lines: list[str] = []
    i = 1
    while i < len(lines) and lines[i].strip() != "---":
        fm_lines.append(lines[i])
        i += 1
    if i >= len(lines):
        return None, text
    try:
        fm = yaml.safe_load("".join(fm_lines))
    except yaml.YAMLError:
        return None, "".join(lines[i + 1:])
    body = "".join(lines[i + 1:])
    return (fm if isinstance(fm, dict) else None), body


def _dump_frontmatter(fm: dict[str, Any], body: str) -> str:
    """Serialize a frontmatter dict + body back to a markdown file string."""
    dumped = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return f"---\n{dumped}---\n{body}"


def _coerce_meta_str(value: object) -> str:
    """Stringify a frontmatter meta value, normalizing YAML-parsed dates.

    ``yaml.safe_load`` turns an unquoted ``2026-07-14`` into a ``datetime.date``
    (and ``2026-07-14 10:30`` into ``datetime.datetime``); a naive ``str()``
    would render the latter with a space. ``isoformat()`` keeps the canonical
    ISO shape so a hand-edited profile.md round-trips cleanly (lenient read).
    """
    if isinstance(value, datetime.date):  # datetime.datetime subclasses date
        return value.isoformat()
    return str(value or "")


def _safe_snapshot_name(value: object) -> str:
    """Render a frontmatter value safe to use as a snapshot filename.

    Strips path separators (and NUL) so a hand-edited ``updated: ../../etc``
    cannot write the snapshot outside ``meta/profile-history/``; also drops a
    leading dot so the file is not hidden from ``*.md`` globs. Reuses
    ``_coerce_meta_str`` so a YAML-parsed date still names the snapshot by its
    ISO string. Empty → ``unknown``.
    """
    text = re.sub(r"[\\/\x00]+", "_", _coerce_meta_str(value)).strip().lstrip(".")
    return text or "unknown"


def _ordered_note_frontmatter(entry: dict[str, Any]) -> dict[str, Any]:
    """Known note keys in stable order, then any unknown keys (e.g. wiki's
    ``sources``/``related``) preserved verbatim. ``__``-prefixed keys (internal
    pass-through like an optional body) are dropped."""
    fm: dict[str, Any] = {k: entry[k] for k in _NOTE_KEY_ORDER if k in entry}
    for key, val in entry.items():
        if key not in fm and not key.startswith("__"):
            fm[key] = val
    return fm


def _note_from_fm(fm: dict[str, Any] | None, body: str = "") -> Note | None:
    if not fm or fm.get("type") != "note":
        return None
    # slice-041: status replaces retired:bool (C-9). A legacy file (pre-migrate)
    # may carry `retired:true` with no `status` — map it so the read path sees
    # the right lifecycle until `trowel memory migrate` backfills `status`.
    status = fm.get("status")
    if not status:
        status = "retired" if fm.get("retired") else "active"
    return Note(
        type="note",
        title=str(fm.get("title", "")),
        tags=tuple(fm.get("tags") or ()),
        kind=fm.get("kind", "fact"),
        summary=str(fm.get("summary", "")),
        created=str(fm.get("created", "")),
        updated=str(fm.get("updated", "")),
        verification=fm.get("verification", "inferred-untested"),
        verification_reason=str(fm.get("verification_reason", "")),
        pain=int(fm.get("pain") or 0),
        pain_reason=str(fm.get("pain_reason", "")),
        conflicts_with=tuple(fm.get("conflicts_with") or ()),
        memory_id=str(fm.get("memory_id", "")),
        status=status,
        supersedes=tuple(fm.get("supersedes") or ()),
        superseded_by=str(fm.get("superseded_by", "")),
        valid_from=str(fm.get("valid_from", "")),
        last_verified_at=str(fm.get("last_verified_at", "")),
        refs=int(fm.get("refs") or 0),
        helpful_refs=int(fm.get("helpful_refs") or 0),
        harmful_refs=int(fm.get("harmful_refs") or 0),
        last_ref=str(fm.get("last_ref", "")),
        trigger=str(fm.get("trigger", "")),
        do_not_use_when=str(fm.get("do_not_use_when", "")),
        sources=tuple(fm.get("sources") or ()),
        source_sessions=tuple(fm.get("source_sessions") or ()),
        content_hash=str(fm.get("content_hash", "")),
        body=body,
    )


def _diary_from_fm(fm: dict[str, Any] | None, body: str = "") -> Diary | None:
    if not fm or fm.get("type") != "diary":
        return None
    return Diary(
        type="diary",
        date=str(fm.get("date", "")),
        layer=fm.get("layer", "day"),
        period=str(fm.get("period", "")),
        promoted_knowledge=tuple(fm.get("promoted_knowledge") or ()),
        body=body,
    )


def _core_item_from_dict(d: object) -> CoreItem | None:
    """Build a CoreItem from one core.md frontmatter item; None if not a mapping.

    The store stays schema-neutral here — ``validate_entry`` is the write-side
    guard; this reader is lenient so a hand-edited core.md never breaks the
    read path (slice-039 injection degrades to fewer items instead of crashing).
    """
    if not isinstance(d, dict):
        return None
    return CoreItem(
        id=str(d.get("id", "")),
        imperative=str(d.get("imperative", "")),
        scope=d.get("scope", "high-risk"),
        status=d.get("status", "seed"),
        source=str(d.get("source", "")),
    )


def _matches(note: Note, filter: dict[str, Any]) -> bool:
    # slice-041: status replaces retired. ``{"status": "active"}`` narrows by
    # lifecycle; ``{"retired": bool}`` is kept as a legacy alias (retired=True
    # → status=="retired", retired=False → status!="retired") so existing
    # callers keep working through the migration.
    if "status" in filter and note.status != filter["status"]:
        return False
    if "retired" in filter:
        want_retired = bool(filter["retired"])
        is_retired = note.status == "retired"
        if want_retired != is_retired:
            return False
    tag = filter.get("tag")
    if tag is not None and tag not in note.tags:
        return False
    return True


_ILLEGAL = re.compile(r'[<>:"\\|?*\x00-\x1f]')
_WS_SLASH = re.compile(r"[\s/]+")


def _slugify(title: str) -> str:
    """Make a title safe to use as a filename stem (keeps CJK)."""
    s = _WS_SLASH.sub("-", title.strip())
    s = _ILLEGAL.sub("", s)
    return s or "untitled"


# ---------------------------------------------------------------- episode IO


_SEG_START = re.compile(r"<!-- @segment (\S+) -->")
_SEG_END = re.compile(r"<!-- @endsegment (\S+) -->")


def _render_segment(
    segment_id: str, diary_entries: tuple[DraftDiary, ...]
) -> tuple[str, str, list[str], str]:
    """Render one segment block (markers + dated events) + its content hash.

    Args:
        segment_id: the stable segment key.
        diary_entries: the distilled DraftDiary tuple (may be empty).

    Returns:
        (block_text, content_hash, activity_dates, empty_reason).
        ``empty_reason`` is ``""`` when the segment has events, else a short
        reason string (also written into the block so the file is self-describing).
    """
    dates: list[str] = []
    if diary_entries:
        inner_parts: list[str] = []
        for d in sorted(diary_entries, key=lambda x: x.date):
            dates.append(d.date)
            inner_parts.append(f"## {d.date}\n\n{d.events.rstrip()}\n")
        inner = "\n".join(inner_parts)
        empty_reason = ""
    else:
        empty_reason = "agent distilled no diary events"
        inner = f"_empty_reason: {empty_reason}_\n"
    block = (
        f"<!-- @segment {segment_id} -->\n"
        f"{inner}"
        f"<!-- @endsegment {segment_id} -->\n"
    )
    content_hash = hashlib.sha256(inner.encode("utf-8")).hexdigest()[:16]
    return block, content_hash, dates, empty_reason


def _parse_segment_blocks(body: str) -> "OrderedDict[str, str]":
    """Parse a segment-marked body into an ordered ``{segment_id: block_text}``.

    Preserves first-seen order so re-upserts replace in place rather than
    appending. Returns an empty dict when the body carries no markers (a fresh
    file). Stray text outside markers is dropped — episodes are marker-delimited
    by contract.

    The end marker's id must MATCH the start marker's id; a mismatched (e.g.
    hand-edited into crossing) pair is treated as an unterminated segment and
    dropped, never silently capturing another segment's content.
    """
    blocks: "OrderedDict[str, str]" = OrderedDict()
    pos = 0
    while True:
        m = _SEG_START.search(body, pos)
        if not m:
            break
        sid = m.group(1)
        # scan for the MATCHING end marker (same id), skipping any inner markers
        # of other ids so crossing pairs can't swallow a sibling segment.
        search_from = m.end()
        while True:
            m2 = _SEG_END.search(body, search_from)
            if not m2:
                break  # unterminated → drop this start
            if m2.group(1) == sid:
                break
            search_from = m2.end()
        if not m2 or m2.group(1) != sid:
            # no matching end marker; advance past this start to keep parsing
            pos = m.end()
            continue
        blocks[sid] = body[m.start() : m2.end()] + "\n"
        pos = m2.end()
    return blocks


def _episode_covers_date(fm: dict[str, Any], date: str) -> bool:
    """Does a (legacy/bare) episode cover ``date``? Top-level activity_dates
    win; a missing set falls back to review_date (oldest episodes only)."""
    ad = fm.get("activity_dates")
    if ad:
        return date in [_coerce_meta_str(d) for d in ad]
    return _coerce_meta_str(fm.get("review_date")) == date


def _segment_entry_for_date(
    block: str, date: str, seg_meta: dict[str, Any]
) -> str | None:
    """The ``## <date>`` body of one segment for ``date``, or None (block-4).

    When the segment carries ``activity_dates`` meta, ``date`` must be in it;
    otherwise (legacy episode) the segment's dates are recovered from its
    headings. Either way the body is sliced from the ``## <date>`` block, so a
    cross-midnight segment contributes only the matching day.
    """
    ad = seg_meta.get("activity_dates")
    if ad:
        # yaml may parse a bare ``2026-07-16`` into a date object; coerce to str.
        ad_str = [_coerce_meta_str(d) for d in ad]
        if date not in ad_str:
            return None
    elif date not in _h2_headings(block):
        return None
    return _extract_h2_block(block, date)


def _h2_headings(block: str) -> list[str]:
    """All ``## <x>`` heading texts in a segment block (in order)."""
    return [ln.strip()[3:] for ln in block.splitlines() if ln.startswith("## ")]


def _extract_h2_block(block: str, date: str) -> str | None:
    """Body under ``## <date>`` until the next heading / endmarker; None if absent."""
    target = f"## {date}"
    out: list[str] = []
    capturing = False
    for ln in block.splitlines():
        if capturing:
            if ln.startswith("## ") or ln.startswith("<!-- @endsegment"):
                break
            out.append(ln)
        elif ln.strip() == target:
            capturing = True
    text = "\n".join(out).strip()
    return text or None
