"""file-backed memory store (slice-038).

Reads/writes the dual-track markdown tree under ``root``:

    root/
      core.md            layer one (always-injected imperatives)
      notes/*.md         knowledge track (layer-two notes)
      dictionary-L0.md   root index (regenerated by slice-041)
      dictionary-L1/     per-domain indexes
      diary/{daily,weekly,monthly}/   experience track

Layer one has NO general write API here (C-5) — only ``seeds.bootstrap_core``
performs the one-time, idempotent seed write. The write loop (040) writes
notes/diary; the read loop (039) reads everything; the tidy loop (041)
rewrites/retires. This module is the shared substrate.
"""
from __future__ import annotations

import hashlib
import logging
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml

from trowel_py.memory.draft import DraftDiary
from trowel_py.memory.schema import validate_entry
from trowel_py.memory.types import CoreItem, Diary, Note, NoteId, PersistContext

logger = logging.getLogger(__name__)

_NOTES_DIR = "notes"
_DIARY_DIR = "diary"
_EPISODES_DIR = "episodes"
_CORE_FILE = "core.md"
_DICT_L0 = "dictionary-L0.md"

# schema layer value (day|week|month) → 038 storage-layout directory name.
# load_diary reads by frontmatter ``layer`` (not dir name), so the two stay
# decoupled; this map keeps write_diary consistent with the 038 convention.
_LAYER_DIR = {"day": "daily", "week": "weekly", "month": "monthly"}

# Stable, readable key order for serialized note frontmatter.
# slice-040-a adds kind (after title), the *_reason / conflicts_with rationale
# block, and the source_sessions / content_hash provenance tail.
_NOTE_KEY_ORDER = (
    "type", "title", "kind", "tags", "summary", "confidence",
    "created", "updated",
    "verification", "verification_reason",
    "pain", "pain_reason", "conflicts_with",
    "refs", "last_ref", "retired",
    "source_sessions", "content_hash",
)


class MemoryStore:
    """Read/write the memory tree rooted at ``root``.

    Args:
        root: the memory root directory (e.g. ``~/.trowel/memory``).
    """

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root)

    # ---- layer one (core) ----
    def load_core(self) -> str:
        """Return core.md full text (empty string if absent). For 039 injection.

        The file carries the imperatives twice: structured in the frontmatter
        ``items`` (the authoritative source 039 should parse) and mirrored in a
        readable numbered body (for humans). If a human edits only the body,
        the two can drift — 039 should treat the frontmatter ``items`` as
        authoritative.
        """
        path = self.root / _CORE_FILE
        return path.read_text(encoding="utf-8") if path.exists() else ""

    # ---- knowledge track (notes) ----
    def load_notes(self, filter: dict[str, Any] | None = None) -> list[Note]:
        """Return all notes (including retired — C-4 retirement ≠ deletion).

        Args:
            filter: optional ``{"retired": bool}`` and/or ``{"tag": str}`` to
                narrow the set (the 039 inject set filters retired out).

        Note:
            Files with no/invalid frontmatter, or whose type is not ``note``,
            are skipped with a warning (W4) — a hand-corrupted note should not
            silently vanish from injection.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return []
        notes: list[Note] = []
        for p in sorted(notes_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if fm is None:
                logger.warning("note %s has no/invalid frontmatter, skipped", p.name)
                continue
            note = _note_from_fm(fm, body)
            if note is None:
                logger.warning("note %s frontmatter type is not 'note', skipped", p.name)
                continue
            notes.append(note)
        if filter:
            notes = [n for n in notes if _matches(n, filter)]
        return notes

    def load_note(self, note_id: NoteId) -> Note | None:
        """Return one note by filename-stem id, or None if absent/invalid.

        slice-040-c: the read tool opens a note by id; this loads one file
        instead of scanning the whole corpus.
        """
        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            return None
        fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if fm is None:
            return None
        return _note_from_fm(fm, body)

    def load_notes_with_id(
        self, filter: dict[str, Any] | None = None
    ) -> list[tuple[NoteId, Note]]:
        """Return ``(note_id, Note)`` pairs (id = filename stem).

        slice-040-c: dictionary clustering needs the stem alongside the note.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return []
        out: list[tuple[NoteId, Note]] = []
        for p in sorted(notes_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if fm is None:
                continue
            note = _note_from_fm(fm, body)
            if note is None:
                continue
            out.append((p.stem, note))
        if filter:
            out = [(i, n) for i, n in out if _matches(n, filter)]
        return out

    def write_note(self, entry: dict[str, Any]) -> NoteId:
        """Validate (C-2/C-3) and persist a note. Returns its filename-stem id.

        Wiki-compatible fields beyond the known set (e.g. ``sources``/``related``)
        are preserved (W3): the known keys are emitted in a stable readable
        order, any unknown keys follow. This keeps write_note symmetric with
        ``record_ref`` (which already preserves unknown keys) and honors the
        "reuse the wiki-compatible subset" intent when migrating wiki notes.

        Raises:
            ValueError: the entry fails schema validation.
        """
        result = validate_entry("note", entry)
        if not result.ok:
            raise ValueError(f"invalid note: {result.errors}")
        slug = self._unique_slug(str(entry.get("title", "")).strip())
        fm = _ordered_note_frontmatter(entry)
        path = self.root / _NOTES_DIR / f"{slug}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_dump_frontmatter(fm, entry.get("__body", "")), encoding="utf-8")
        return slug

    def write_diary(self, entry: dict[str, Any]) -> str:
        """Validate (C-2) and persist a diary entry. Returns its date stem.

        The file lands under ``diary/{daily|weekly|monthly}/{date}.md`` — the
        directory name follows the 038 storage-layout convention, while the
        frontmatter ``layer`` value stays the schema value (``day|week|month``).
        ``write_diary`` maps layer→dir so callers always pass the schema layer.

        The event-stream body is passed via the ``__body`` internal channel
        (same convention as ``write_note``); it lands in the file body, not in
        frontmatter. Same-date writes overwrite (a diary day is one file).

        Raises:
            ValueError: the entry fails schema validation (e.g. missing date,
                illegal layer).
        """
        fm = {k: v for k, v in entry.items() if not k.startswith("__")}
        fm["type"] = "diary"
        result = validate_entry("diary", fm)
        if not result.ok:
            raise ValueError(f"invalid diary: {result.errors}")
        layer = str(fm.get("layer", "day"))
        date = str(fm.get("date", ""))
        dir_name = _LAYER_DIR.get(layer, "daily")
        path = self.root / _DIARY_DIR / dir_name / f"{date}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_dump_frontmatter(fm, entry.get("__body", "")), encoding="utf-8")
        return date

    def record_ref(self, note_id: NoteId, date: str) -> None:
        """Increment refs and stamp last_ref on an existing note (retirement input).

        slice-040-c: per-note ``fcntl.flock`` so concurrent MCP servers don't
        lose refs increments (read-modify-write race — access-log append is
        atomic via O_APPEND, but the refs rewrite is not).

        Raises:
            FileNotFoundError: no note with that id.
        """
        import fcntl

        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            raise FileNotFoundError(note_id)
        with path.open("r+", encoding="utf-8") as f:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
            try:
                fm, body = _split_frontmatter(f.read())
                if fm is None:
                    raise ValueError(f"note {note_id!r} has no frontmatter")
                fm["refs"] = int(fm.get("refs") or 0) + 1
                fm["last_ref"] = date
                f.seek(0)
                f.truncate()
                f.write(_dump_frontmatter(fm, body))
            finally:
                fcntl.flock(f.fileno(), fcntl.LOCK_UN)

    def find_note_by_source(self, cc_session_id: str, content_hash: str) -> NoteId | None:
        """Return the id of the note from ``cc_session_id`` with this content_hash.

        slice-040-a idempotence key (D4): ``(cc_session_id, content_hash)``. A
        re-run with the same source+content finds the existing note so persist
        updates mutable fields instead of duplicating. Returns ``None`` when no
        note carries that source session + hash (existing 45 notes predate this
        field and are skipped — they simply become new writes once).

        TODO(041): this is O(n) per call — ``persist_draft`` calls it once per
        draft note, so the whole landing is O(notes × existing_notes). Fine at
        the current corpus size (tens); build an in-memory
        ``(cc_session_id, content_hash) → id`` index when notes reach hundreds.
        """
        notes_dir = self.root / _NOTES_DIR
        if not notes_dir.exists():
            return None
        for p in sorted(notes_dir.glob("*.md")):
            fm, _body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if not fm:
                continue
            sources = fm.get("source_sessions") or []
            if cc_session_id in sources and fm.get("content_hash") == content_hash:
                return p.stem
        return None

    def update_note_fields(self, note_id: NoteId, fields: dict[str, Any]) -> None:
        """Read-modify-write a note's frontmatter fields (idempotent re-judge path).

        Only the mutable judgment fields are ever updated this way
        (verification / pain / *_reason / conflicts_with / updated / refs …);
        the title/summary/body/kind identity is stable (their hash is the key).
        Preserves unknown wiki fields and the body (W3 symmetry with record_ref).

        Raises:
            FileNotFoundError: no note with that id.
        """
        path = self.root / _NOTES_DIR / f"{note_id}.md"
        if not path.exists():
            raise FileNotFoundError(note_id)
        fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if fm is None:
            raise ValueError(f"note {note_id!r} has no frontmatter")
        fm.update(fields)
        path.write_text(_dump_frontmatter(fm, body), encoding="utf-8")

    # ---- experience track (diary) ----
    def load_diary(self, since: str | None = None,
                   layer: str | None = None) -> list[Diary]:
        """Return diary entries, optionally filtered by date floor and layer.

        ``since`` is a lexicographic floor on the ``date`` string (inclusive);
        callers should use ISO ``YYYY-MM-DD`` dates so the ordering is correct
        (W2 — the schema does not yet enforce ISO format).
        """
        diary_root = self.root / _DIARY_DIR
        if not diary_root.exists():
            return []
        out: list[Diary] = []
        for p in sorted(diary_root.rglob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            d = _diary_from_fm(fm, body)
            if d is None:
                continue
            if layer and d.layer != layer:
                continue
            if since and d.date < since:
                continue
            out.append(d)
        return out

    # ---- experience track (episodes) — slice-040-a ----
    def write_episode(
        self, context: PersistContext, diary_entries: tuple[DraftDiary, ...]
    ) -> str:
        """Upsert one segment into ``episodes/<cc_session_id>.md`` (C-1).

        One source session maps to exactly one episode file; the file may hold
        multiple segments (040-b incremental re-runs). This call upserts the
        ``context.segment_id`` segment: a same-id segment replaces only its own
        body, a new-id segment is appended — an existing sibling segment is
        never clobbered, so the original experience is never lost.

        ``diary_entries`` come straight from the distilled DraftDiary tuple; a
        session whose agent returned zero events still gets a skeletal segment
        flagged ``empty_reason`` (no silent skip → no lost provenance).

        Returns:
            the ``cc_session_id`` (the episode filename stem).
        """
        path = self.root / _EPISODES_DIR / f"{context.cc_session_id}.md"
        path.parent.mkdir(parents=True, exist_ok=True)

        if path.exists():
            fm, body = _split_frontmatter(path.read_text(encoding="utf-8"))
            fm = fm or {}
            blocks = _parse_segment_blocks(body)
            segs = list(fm.get("segments") or [])
            prior_dates = set(fm.get("activity_dates") or [])
        else:
            fm, body = {}, ""
            blocks = _parse_segment_blocks(body)
            segs = []
            prior_dates = set()

        block_text, content_hash, dates, empty_reason = _render_segment(
            context.segment_id, diary_entries
        )
        # upsert block (preserve insertion order; replace in place if exists)
        blocks[context.segment_id] = block_text
        # upsert segment metadata (replace in place, else append)
        seg_meta: dict[str, Any] = {
            "segment_id": context.segment_id,
            "start_offset": context.source_start_offset,
            "end_offset": context.source_end_offset,
            "review_date": context.review_date,
            "content_hash": content_hash,
        }
        if empty_reason:
            seg_meta["empty_reason"] = empty_reason
        new_segs: list[dict[str, Any]] = []
        replaced = False
        for s in segs:
            if s.get("segment_id") == context.segment_id:
                new_segs.append(seg_meta)
                replaced = True
            else:
                new_segs.append(s)
        if not replaced:
            new_segs.append(seg_meta)

        fm_out: dict[str, Any] = {
            "type": "episode",
            "cc_session_id": context.cc_session_id,
            "workdir": context.workdir,
            "registered_at": context.registered_at,
            "review_date": context.review_date,
            "activity_dates": sorted(prior_dates | set(dates)),
            "source_jsonl": context.source_jsonl,
            "segments": new_segs,
        }
        body_out = "".join(blocks.values())
        path.write_text(_dump_frontmatter(fm_out, body_out), encoding="utf-8")
        return context.cc_session_id

    def derive_daily_from_episodes(self, date: str) -> str:
        """Rebuild ``diary/daily/<date>.md`` as the aggregate of that day's episodes.

        C-8: the daily file is a *derived cache* of episodes, never the source
        of truth. Reads every ``episodes/*.md`` whose ``review_date`` == ``date``,
        orders them by ``registered_at`` (time order, not filename order), and
        concatenates their segment bodies into one daily body via
        ``write_diary`` (same-date overwrite = rebuild).

        Returns:
            the date stem, or ``""`` when no episode matches (no fabricated
            empty daily — preserves 039's "empty = nothing happened" contract).
        """
        eps_dir = self.root / _EPISODES_DIR
        if not eps_dir.exists():
            return ""
        items: list[tuple[str, str]] = []
        for p in sorted(eps_dir.glob("*.md")):
            fm, body = _split_frontmatter(p.read_text(encoding="utf-8"))
            if not fm or fm.get("review_date") != date:
                continue
            items.append((str(fm.get("registered_at", "")), body))
        if not items:
            return ""
        items.sort(key=lambda x: x[0])
        daily_body = "\n\n".join(body for _ts, body in items)
        self.write_diary(
            {
                "type": "diary",
                "date": date,
                "layer": "day",
                "period": date,
                "promoted_knowledge": [],
                "__body": daily_body,
            }
        )
        return date

    # ---- dictionary ----
    def load_dictionary_L0(self) -> str:
        """Return the L0 root index text (empty string if skeleton absent)."""
        path = self.root / _DICT_L0
        return path.read_text(encoding="utf-8") if path.exists() else ""

    # ---- layer-one items (structured, for slice-039 injection) ----
    def load_core_items(self) -> tuple[CoreItem, ...]:
        """Parse core.md frontmatter items into CoreItem (all, including retired).

        The store stays neutral — retirement filtering is the injection layer's
        job (slice-039 C-1/C-2). Returns () when core.md is absent, has no
        frontmatter, or carries no ``items`` list.
        """
        path = self.root / _CORE_FILE
        if not path.exists():
            return ()
        fm, _body = _split_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            return ()
        items = fm.get("items")
        if not isinstance(items, list):
            return ()
        return tuple(
            core_item
            for it in items
            if (core_item := _core_item_from_dict(it)) is not None
        )

    # ---- internals ----
    def _unique_slug(self, title: str) -> str:
        base = _slugify(title)
        slug, i = base, 2
        while (self.root / _NOTES_DIR / f"{slug}.md").exists():
            slug, i = f"{base}-{i}", i + 1
        return slug


# ---------------------------------------------------------------- frontmatter IO


def _split_frontmatter(text: str) -> tuple[dict[str, Any] | None, str]:
    """Split a ``---``-delimited YAML frontmatter block from the body.

    Returns:
        (frontmatter dict or None, body text). None frontmatter when the file
        has no well-formed leading block.
    """
    if not text.startswith("---"):
        return None, text
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return None, text
    fm_lines: list[str] = []
    i = 1
    while i < len(lines) and lines[i].strip() != "---":
        fm_lines.append(lines[i])
        i += 1
    if i >= len(lines):
        return None, text
    try:
        fm = yaml.safe_load("".join(fm_lines))
    except yaml.YAMLError:
        return None, "".join(lines[i + 1:])
    body = "".join(lines[i + 1:])
    return (fm if isinstance(fm, dict) else None), body


def _dump_frontmatter(fm: dict[str, Any], body: str) -> str:
    """Serialize a frontmatter dict + body back to a markdown file string."""
    dumped = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, default_flow_style=False)
    return f"---\n{dumped}---\n{body}"


def _ordered_note_frontmatter(entry: dict[str, Any]) -> dict[str, Any]:
    """Known note keys in stable order, then any unknown keys (e.g. wiki's
    ``sources``/``related``) preserved verbatim. ``__``-prefixed keys (internal
    pass-through like an optional body) are dropped."""
    fm: dict[str, Any] = {k: entry[k] for k in _NOTE_KEY_ORDER if k in entry}
    for key, val in entry.items():
        if key not in fm and not key.startswith("__"):
            fm[key] = val
    return fm


def _note_from_fm(fm: dict[str, Any] | None, body: str = "") -> Note | None:
    if not fm or fm.get("type") != "note":
        return None
    return Note(
        type="note",
        title=str(fm.get("title", "")),
        tags=tuple(fm.get("tags") or ()),
        kind=fm.get("kind", "fact"),
        summary=str(fm.get("summary", "")),
        confidence=fm.get("confidence", "draft"),
        created=str(fm.get("created", "")),
        updated=str(fm.get("updated", "")),
        verification=fm.get("verification", "inferred-untested"),
        verification_reason=str(fm.get("verification_reason", "")),
        pain=int(fm.get("pain") or 0),
        pain_reason=str(fm.get("pain_reason", "")),
        conflicts_with=tuple(fm.get("conflicts_with") or ()),
        refs=int(fm.get("refs") or 0),
        last_ref=str(fm.get("last_ref", "")),
        retired=bool(fm.get("retired", False)),
        source_sessions=tuple(fm.get("source_sessions") or ()),
        content_hash=str(fm.get("content_hash", "")),
        body=body,
    )


def _diary_from_fm(fm: dict[str, Any] | None, body: str = "") -> Diary | None:
    if not fm or fm.get("type") != "diary":
        return None
    return Diary(
        type="diary",
        date=str(fm.get("date", "")),
        layer=fm.get("layer", "day"),
        period=str(fm.get("period", "")),
        promoted_knowledge=tuple(fm.get("promoted_knowledge") or ()),
        body=body,
    )


def _core_item_from_dict(d: object) -> CoreItem | None:
    """Build a CoreItem from one core.md frontmatter item; None if not a mapping.

    The store stays schema-neutral here — ``validate_entry`` is the write-side
    guard; this reader is lenient so a hand-edited core.md never breaks the
    read path (slice-039 injection degrades to fewer items instead of crashing).
    """
    if not isinstance(d, dict):
        return None
    return CoreItem(
        id=str(d.get("id", "")),
        imperative=str(d.get("imperative", "")),
        scope=d.get("scope", "high-risk"),
        status=d.get("status", "seed"),
        source=str(d.get("source", "")),
    )


def _matches(note: Note, filter: dict[str, Any]) -> bool:
    if "retired" in filter and note.retired != filter["retired"]:
        return False
    tag = filter.get("tag")
    if tag is not None and tag not in note.tags:
        return False
    return True


_ILLEGAL = re.compile(r'[<>:"\\|?*\x00-\x1f]')
_WS_SLASH = re.compile(r"[\s/]+")


def _slugify(title: str) -> str:
    """Make a title safe to use as a filename stem (keeps CJK)."""
    s = _WS_SLASH.sub("-", title.strip())
    s = _ILLEGAL.sub("", s)
    return s or "untitled"


# ---------------------------------------------------------------- episode IO


_SEG_START = re.compile(r"<!-- @segment (\S+) -->")
_SEG_END = re.compile(r"<!-- @endsegment (\S+) -->")


def _render_segment(
    segment_id: str, diary_entries: tuple[DraftDiary, ...]
) -> tuple[str, str, list[str], str]:
    """Render one segment block (markers + dated events) + its content hash.

    Args:
        segment_id: the stable segment key.
        diary_entries: the distilled DraftDiary tuple (may be empty).

    Returns:
        (block_text, content_hash, activity_dates, empty_reason).
        ``empty_reason`` is ``""`` when the segment has events, else a short
        reason string (also written into the block so the file is self-describing).
    """
    dates: list[str] = []
    if diary_entries:
        inner_parts: list[str] = []
        for d in sorted(diary_entries, key=lambda x: x.date):
            dates.append(d.date)
            inner_parts.append(f"## {d.date}\n\n{d.events.rstrip()}\n")
        inner = "\n".join(inner_parts)
        empty_reason = ""
    else:
        empty_reason = "agent distilled no diary events"
        inner = f"_empty_reason: {empty_reason}_\n"
    block = (
        f"<!-- @segment {segment_id} -->\n"
        f"{inner}"
        f"<!-- @endsegment {segment_id} -->\n"
    )
    content_hash = hashlib.sha256(inner.encode("utf-8")).hexdigest()[:16]
    return block, content_hash, dates, empty_reason


def _parse_segment_blocks(body: str) -> "OrderedDict[str, str]":
    """Parse a segment-marked body into an ordered ``{segment_id: block_text}``.

    Preserves first-seen order so re-upserts replace in place rather than
    appending. Returns an empty dict when the body carries no markers (a fresh
    file). Stray text outside markers is dropped — episodes are marker-delimited
    by contract.

    The end marker's id must MATCH the start marker's id; a mismatched (e.g.
    hand-edited into crossing) pair is treated as an unterminated segment and
    dropped, never silently capturing another segment's content.
    """
    blocks: "OrderedDict[str, str]" = OrderedDict()
    pos = 0
    while True:
        m = _SEG_START.search(body, pos)
        if not m:
            break
        sid = m.group(1)
        # scan for the MATCHING end marker (same id), skipping any inner markers
        # of other ids so crossing pairs can't swallow a sibling segment.
        search_from = m.end()
        while True:
            m2 = _SEG_END.search(body, search_from)
            if not m2:
                break  # unterminated → drop this start
            if m2.group(1) == sid:
                break
            search_from = m2.end()
        if not m2 or m2.group(1) != sid:
            # no matching end marker; advance past this start to keep parsing
            pos = m.end()
            continue
        blocks[sid] = body[m.start() : m2.end()] + "\n"
        pos = m2.end()
    return blocks
