"""value objects for the memory store (slice-038).

Frozen dataclasses throughout (immutability — see global coding-style). The
frontmatter field names reuse the wiki-compatible subset (title/tags/summary/
confidence/created/updated) and extend it with memory-only fields
(verification/refs/last_ref/retired/pain).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

#: a note id is its filename stem (stable, human-readable).
NoteId = str

EntryType = Literal["core", "note", "diary", "dictionary"]

Confidence = Literal["draft", "evolving", "stable"]
Verification = Literal["verified", "inferred-untested", "event-data-supported"]
DiaryLayer = Literal["day", "week", "month"]
DictionaryLayer = Literal["L0", "L1"]
Scope = Literal["high-risk", "low-risk"]
CoreStatus = Literal["seed", "active", "retired"]


@dataclass(frozen=True)
class ValidationResult:
    """Outcome of validating one frontmatter payload.

    Attributes:
        ok: True iff the payload satisfies the schema for its type.
        errors: human-readable validation failures (empty when ok).
    """

    ok: bool
    errors: tuple[str, ...] = ()


@dataclass(frozen=True)
class CoreItem:
    """One layer-one imperative (a value / hard rule).

    Attributes:
        id: stable identifier used in promoted_knowledge / refs.
        imperative: the rule text, imperative voice.
        scope: high-risk rules walk the full lookup chain; low-risk allow fast
            assumptions (防 ownership 表演).
        status: seed (probation) | active | retired.
        source: where this seed was derived from.
    """

    id: str
    imperative: str
    scope: Scope = "high-risk"
    status: CoreStatus = "seed"
    source: str = ""


@dataclass(frozen=True)
class Core:
    """Layer-one container: the always-injected imperatives."""

    items: tuple[CoreItem, ...]


@dataclass(frozen=True)
class Note:
    """A layer-two knowledge note (the reusable-conclusion track).

    Fields ``title``/``tags``/``summary``/``confidence``/``created``/``updated``
    are wiki-compatible; the rest are memory-only.
    """

    type: Literal["note"]
    title: str
    tags: tuple[str, ...] = ()
    summary: str = ""
    confidence: Confidence = "draft"
    created: str = ""
    updated: str = ""
    verification: Verification = "inferred-untested"
    refs: int = 0
    last_ref: str = ""
    retired: bool = False
    pain: int = 0


@dataclass(frozen=True)
class Diary:
    """An experience-track entry (event stream: time / what / where-stuck / pain).

    Attributes:
        date: ISO date of the entry.
        layer: compression level (day | week | month).
        period: the interval this entry covers (e.g. a week range).
        promoted_knowledge: note ids already lifted out into notes/ (dedupe).
    """

    type: Literal["diary"]
    date: str
    layer: DiaryLayer = "day"
    period: str = ""
    promoted_knowledge: tuple[str, ...] = ()
    body: str = ""


@dataclass(frozen=True)
class DictionaryEntry:
    """A dictionary index node (L0 root overview, or one L1 domain index).

    The body (titles + summaries + triggers) is regenerated by slice-041; here
    we only pin the frontmatter shape.
    """

    type: Literal["dictionary"]
    layer: DictionaryLayer
    domain: str = ""
