"""value objects for the memory store (slice-038).

Frozen dataclasses throughout (immutability — see global coding-style). The
frontmatter field names reuse the wiki-compatible subset (title/tags/summary/
confidence/created/updated) and extend it with memory-only fields
(verification/refs/last_ref/retired/pain).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

#: a note id is its filename stem (stable, human-readable).
NoteId = str

EntryType = Literal["core", "note", "diary", "dictionary"]

Confidence = Literal["draft", "evolving", "stable"]
Verification = Literal["verified", "inferred-untested", "event-data-supported"]
DiaryLayer = Literal["day", "week", "month"]
DictionaryLayer = Literal["L0", "L1"]
Scope = Literal["high-risk", "low-risk"]
CoreStatus = Literal["seed", "active", "retired"]
NoteKind = Literal["fact", "gotcha", "procedure", "preference", "hypothesis"]


@dataclass(frozen=True)
class ValidationResult:
    """Outcome of validating one frontmatter payload.

    Attributes:
        ok: True iff the payload satisfies the schema for its type.
        errors: human-readable validation failures (empty when ok).
    """

    ok: bool
    errors: tuple[str, ...] = ()


@dataclass(frozen=True)
class CoreItem:
    """One layer-one imperative (a value / hard rule).

    Attributes:
        id: stable identifier used in promoted_knowledge / refs.
        imperative: the rule text, imperative voice.
        scope: high-risk rules walk the full lookup chain; low-risk allow fast
            assumptions (防 ownership 表演).
        status: seed (probation) | active | retired.
        source: where this seed was derived from.
    """

    id: str
    imperative: str
    scope: Scope = "high-risk"
    status: CoreStatus = "seed"
    source: str = ""


@dataclass(frozen=True)
class Core:
    """Layer-one container: the always-injected imperatives."""

    items: tuple[CoreItem, ...]


@dataclass(frozen=True)
class Note:
    """A layer-two knowledge note (the reusable-conclusion track).

    Fields ``title``/``tags``/``summary``/``confidence``/``created``/``updated``
    are wiki-compatible; the rest are memory-only.

    slice-040-a adds:
        kind: procedural-memory classifier (fact | gotcha | procedure | …).
            Defaults to ``fact`` so the existing 45 notes (no kind field) load
            unchanged. ``procedure`` notes carry trigger/procedure/stop/
            anti-pattern in the body.
        verification_reason / pain_reason / conflicts_with: the agent's
            ``why this tier / why this score / which existing notes this
            contradicts`` rationale — persisted, never evaporated (P2).
        source_sessions / content_hash: provenance for idempotent re-runs and
            future correction (041). content_hash = sha256(title+summary+body+
            kind); (cc_session_id, hash) is the dedupe key.
    """

    type: Literal["note"]
    title: str
    tags: tuple[str, ...] = ()
    kind: NoteKind = "fact"
    summary: str = ""
    confidence: Confidence = "draft"
    created: str = ""
    updated: str = ""
    verification: Verification = "inferred-untested"
    verification_reason: str = ""
    pain: int = 0
    pain_reason: str = ""
    conflicts_with: tuple[str, ...] = ()
    refs: int = 0
    last_ref: str = ""
    retired: bool = False
    source_sessions: tuple[str, ...] = ()
    content_hash: str = ""
    body: str = ""


@dataclass(frozen=True)
class Diary:
    """An experience-track entry (event stream: time / what / where-stuck / pain).

    Attributes:
        date: ISO date of the entry.
        layer: compression level (day | week | month).
        period: the interval this entry covers (e.g. a week range).
        promoted_knowledge: note ids already lifted out into notes/ (dedupe).
    """

    type: Literal["diary"]
    date: str
    layer: DiaryLayer = "day"
    period: str = ""
    promoted_knowledge: tuple[str, ...] = ()
    body: str = ""


@dataclass(frozen=True)
class DictionaryEntry:
    """A dictionary index node (L0 root overview, or one L1 domain index).

    The body (titles + summaries + triggers) is regenerated by slice-041; here
    we only pin the frontmatter shape.
    """

    type: Literal["dictionary"]
    layer: DictionaryLayer
    domain: str = ""


@dataclass(frozen=True)
class PersistContext:
    """Provenance for landing one distilled session (slice-040-a).

    Built by ``run_daily_review`` from the SessionRecord and passed alongside
    the Draft to ``persist_draft`` — persist MUST NOT guess its source. One
    source session maps to exactly one episode file (``episodes/<cc_session_id>
    .md``) but may grow multiple incremental segments across re-runs; 040-a
    uses a single whole-file segment ``<cc_session_id>:0:end``, 040-b reuses
    the same contract with incremental offsets.

    Attributes:
        segment_id: stable segment key (``<cc_session_id>:<start>:<end>``).
        cc_session_id: cc's uuid session id (the jsonl filename stem).
        workdir: the session's working directory.
        registered_at: ISO timestamp the session was registered.
        review_date: ISO ``YYYY-MM-DD`` the review runs for (= session.date).
        source_jsonl: absolute path to the cc session jsonl.
        source_start_offset: byte offset the segment starts at (0 for 040-a).
        source_end_offset: byte offset the segment ends at (None = EOF).
    """

    segment_id: str
    cc_session_id: str
    workdir: str
    registered_at: str
    review_date: str
    source_jsonl: str
    source_start_offset: int = 0
    source_end_offset: int | None = None
