"""Model OS 的稳定公开入口。

事务 Store 与 append-only journal 保存 Task、WorkItem、Episode、lease 和决策事实；
纯 reducer 从日志派生快照，写入前统一脱敏。Self Manifest 只由 runtime 事实组装。
WorkBroker 仲裁 foreground/default/maintenance 的 provider、预算和并发资源，并以
lease/fencing 约束崩溃恢复和用量归因。

Scheduler、Router、Episode Runner 及 memory scheduler 接入不属于本包当前实现。
"""

from trowel_py.model_os.redaction import redact_payload
from trowel_py.model_os.reducer import (
    EpisodeState,
    Snapshot,
    TaskState,
    WorkItemState,
    initial_snapshot,
    reduce_decision,
    reduce_event,
)
from trowel_py.model_os.store import (
    EpisodeCommandError,
    ForegroundConflict,
    LeaseConflict,
    ModelOsStore,
    StaleWriterRejected,
    TaskCommandError,
    WarmFull,
)
from trowel_py.model_os.types import (
    ArtifactRef,
    CompletionEvidence,
    DecisionRecord,
    Episode,
    EpisodeSnapshot,
    EpisodeStatus,
    ErrorRecord,
    EventEnvelope,
    EventKind,
    Lease,
    MemoryEligibility,
    PendingDescriptor,
    Provenance,
    ReconcileReason,
    SelfManifest,
    SessionPurpose,
    SideEffectRecord,
    SnapshotRef,
    SnapshotSource,
    SubsystemState,
    Task,
    TaskOrigin,
    TaskStatus,
    WaitingCondition,
    WaitingSubtype,
    WorkItem,
    WorkItemKind,
    WorkItemStatus,
)
from trowel_py.model_os.work_broker import (
    BrokerPolicy,
    BudgetDimensions,
    CatchupPolicy,
    DenialReason,
    IdempotencyConflict,
    ModelTier,
    StaleWorkLease,
    UsageRecord,
    UsageTotals,
    WorkBroker,
    WorkDenial,
    WorkKind,
    WorkLease,
    WorkRequest,
)

__all__ = [
    "ArtifactRef",
    "BrokerPolicy",
    "BudgetDimensions",
    "CatchupPolicy",
    "CompletionEvidence",
    "DecisionRecord",
    "DenialReason",
    "Episode",
    "EpisodeCommandError",
    "EpisodeSnapshot",
    "EpisodeState",
    "EpisodeStatus",
    "ErrorRecord",
    "EventEnvelope",
    "EventKind",
    "ForegroundConflict",
    "IdempotencyConflict",
    "Lease",
    "LeaseConflict",
    "MemoryEligibility",
    "ModelTier",
    "ModelOsStore",
    "PendingDescriptor",
    "Provenance",
    "ReconcileReason",
    "SelfManifest",
    "SessionPurpose",
    "SideEffectRecord",
    "Snapshot",
    "SnapshotRef",
    "SnapshotSource",
    "StaleWorkLease",
    "StaleWriterRejected",
    "SubsystemState",
    "Task",
    "TaskCommandError",
    "TaskOrigin",
    "TaskState",
    "TaskStatus",
    "UsageRecord",
    "UsageTotals",
    "WaitingCondition",
    "WaitingSubtype",
    "WarmFull",
    "WorkBroker",
    "WorkDenial",
    "WorkItem",
    "WorkItemKind",
    "WorkItemStatus",
    "WorkItemState",
    "WorkKind",
    "WorkLease",
    "WorkRequest",
    "initial_snapshot",
    "redact_payload",
    "reduce_decision",
    "reduce_event",
]
