versionConstraint: '=2.4.6'

projects:
  root: '.'
  web: 'web'
  e2e: 'e2e'

defaultProject: 'root'

vcs:
  defaultBranch: 'main'

pipeline:
  syncWorkspace: false
  syncProjects: false

telemetry: false
